### PR TITLE
Immutability on the wrapper classes

### PR DESCRIPTION
**Pull request by olijeffers0n**

### CODE REVIEW

**Review by GodCipher — CHANGES_REQUESTED** [review]
For centralization: As we already spoke about, this is fine, as long as you change the method names to something, which does not imply, that another object was created for the mutation.

**Comment by olijeffers0n** [comment]
Looking at this, there is no "good" way to make the user aware that an operation such as `setX` will create a new object. Personally I think this is fine as it fixes a lot of the mutability issues people often encounter with the bukkit API.

**Comment by olijeffers0n** [comment]
RE your comment. I cannot use discord at school as it is blocked so yes, comment here please

**Comment by olijeffers0n** [comment]
Rebased

**Comment by GodCipher** [comment]
I personally don't see which mutability issues the people would face here. Also this is not quite an enhancement but an for now insignificant change which does effectively nothing but creating a few more redundant throwaway objects. The Bukkit-API is a good point, since our api, especially the wrappers, are meant to adapt to that - and its mutable.

"Never change a running system" & "Premature optimization is the root of all evil" fits here very well.

I am against this as long as there is no urgency or other significant benefits.

**Comment by GodCipher** [comment]
[fuck it](https://github.com/olijeffers0n/Pathetic/commit/9b640559c2644e869f92243f4ca27dfb5cd5b715)

**Comment by olijeffers0n** [comment]
Lmao

**Pull request merged**
